### ISSUE TITLE
Can u give me a example to how to test it

### ISSUE THREAD

**Issue by anthonyyuan** [vitoralbiero/face_analysis_pytorch#1]

**Comment by anthonyyuan** [comment]
parser.add_argument('--source', '-s', help='Path to the images.')
    parser.add_argument('--image_list', '-i', help='File with images names.')

**Comment by anthonyyuan** [comment]
how to use it ,if I have only one picure

**Comment by vitoralbiero** [comment]
I updated the readme file with instructions. Basically, the source is the path to the main folder where the images are and the image list contains the paths from that folder to each image. If you have only one image, go to the folder where this image is, and run ls * > images.txt. Then, pass the images.txt along with the path to the folder where the image was. If you have multiple subfolders, run find ./ -type f > images.txt instead to create paths with sub dirs to the images. Right now you will need to align your image prior since I am still adding a detector to the predict method.
